name: test

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: install system deps
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

      - uses: dtolnay/rust-toolchain@1.71
      - run: cargo build

      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

      - name: test tauri example
        run: |
          cd examples/tauri/src-tauri
          cargo test --features tauri/custom-protocol
