framework = "WebKit"
crate = "objc2-web-kit"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
macos = "10.2"
maccatalyst = "13.0"
ios = "16.0"
visionos = "1.0"

# Not marked as nullable, but should be.
class.WKNavigationAction.methods.sourceFrame.return.nullability = "nullable"

# Needs `nw_proxy_config_t` from the Network framework
class.WKWebsiteDataStore.methods.proxyConfigurations.skipped = true
class.WKWebsiteDataStore.methods."setProxyConfigurations:".skipped = true
