name: Fetch ONNX Runtime

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: windows-latest
    steps:
      - name: Placeholder
        run: echo "TODO: implement download and cache of ORT DirectML packages"
